# Generated by Django 2.1.7 on 2019-11-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
