# Generated by Django 2.2.7 on 2019-12-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='icons',
            field=models.CharField(default='/static/default.jpg', max_length=50),
        ),
    ]
