# Generated by Django 2.2.7 on 2019-12-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_icons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='icons',
            new_name='icon',
        ),
    ]
