# Generated by Django 2.2.7 on 2019-12-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191203_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='/common_static/default.jpg', max_length=500),
        ),
    ]
