# Generated by Django 2.2.7 on 2019-12-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191202_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='icon',
            new_name='avator',
        ),
    ]
