# Generated by Django 2.2.7 on 2019-12-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191202_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avator',
            new_name='avatar',
        ),
    ]
