# Generated by Django 2.2.5 on 2019-11-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lists',
        ),
    ]
