# Generated by Django 2.2.7 on 2019-11-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('DatasetName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Description', models.IntegerField()),
                ('Score', models.BooleanField()),
                ('Time', models.DateTimeField()),
            ],
        ),
    ]
