# Generated by Django 2.2.7 on 2019-11-28 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=50)),
                ('Score', models.IntegerField()),
                ('Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Like', models.IntegerField(default=0)),
            ],
        ),
    ]
