# Generated by Django 2.1.7 on 2019-12-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='DatasetName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_dn', to='dataset.dataset'),
        ),
    ]
