# Generated by Django 2.2.7 on 2019-11-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Description',
            field=models.CharField(max_length=50),
        ),
    ]
