# Generated by Django 2.2.7 on 2019-11-28 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='DatasetName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.dataset'),
        ),
    ]
