# Generated by Django 2.2.7 on 2019-11-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Like',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
