# Generated by Django 2.1.7 on 2019-12-02 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0002_star_datasetname'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='DatasetName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.dataset'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
