# Generated by Django 2.2.7 on 2019-11-14 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20191114_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
