# Generated by Django 2.2.7 on 2019-11-28 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataset', '0003_auto_20191128_1615'),
        ('comment', '0003_comment_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='likelike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DatasetName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.dataset')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
