# Generated by Django 2.1.7 on 2019-11-29 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0003_auto_20191129_1340'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0003_auto_20191128_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DatasetName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_dn', to='dataset.dataset')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='likelike',
            name='DatasetName',
        ),
        migrations.RemoveField(
            model_name='likelike',
            name='Username',
        ),
        migrations.DeleteModel(
            name='likelike',
        ),
    ]
