# Generated by Django 2.2.7 on 2019-11-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Like',
            field=models.IntegerField(default=0),
        ),
    ]
