# Generated by Django 2.2.7 on 2019-12-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20191129_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Description',
            field=models.CharField(max_length=1000),
        ),
    ]
